### ISSUE TITLE
Possible breaking change with v1.1.0

### ISSUE THREAD

**Issue by skinread** [react-bootstrap/react-overlays#278]
Hi, I have react-bootstrap@next included in my project and since react-overlays v1.1.0 release today, I'm seeing an error during build that I suspect is from 1.1.0. If I fix the version back to react-overlays 1.0.0 the error is no longer present.

Some of the log

```
> Failed to build
{ Error: (client) ./node_modules/react-bootstrap/es/Dropdown.js
Module not found: Error: Can't resolve 'react-overlays/Dropdown' in '/Users/Sean.Kinread/next-now/node_modules/react-bootstrap/es'
 @ ./node_modules/react-bootstrap/es/Dropdown.js 7:0-51 73:27-39 91:52-64
 @ ./node_modules/react-bootstrap/es/index.js
 @ ./pages/_error.js
 @ multi ./pages/_error.js
    at /Users/Sean.Kinread/next-now/node_modules/next/dist/build/index.js:144:31
    at finalCallback (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/Users/Sean.Kinread/next-now/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/Compiler.js:204:39)
    at hooks.done.callAsync.err (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/Compiler.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Sean.Kinread/next-now/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Sean.Kinread/next-now/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/Compiler.js:218:21)
    at hooks.afterCompile.callAsync.err (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/Sean.Kinread/next-now/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/Sean.Kinread/next-now/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/Sean.Kinread/next-now/node_modules/webpack/lib/Compiler.js:544:30)
```

**Comment by jquense** [comment]
sorry folks fixed in `1.1.1`
